---
- hosts: webservers 
  vars_files: 
    - vars/main.yml
#    - vars/apache_customers_settings.yml
  
#  pre_tasks:
#    - name: create documentroot on servers
#      hosts={{ item.hostname }}
#    
#      set_fact:
#            file: "{{ apache_vhosts | default([])+ [{'path': item.documentroot}]}}"
#    - name: create vhost files
#      set_facts:
#            apache_vhosts: "{{ apache_vhosts | default([])+ [{'servername:': item.url, 'documentroot': item.documentroot}]}}"
#
#      with_items: "{{ customers_apache_vhosts }}"

  pre_tasks:
    - name: creation du documentroot
      file: path="{{ item.documentroot }}" state=directory
    - name: copy index.html to the documentroot folder
      src:  templates/index.html
      dest: /var/www/html/index.html
      with_items: "{{customers_apache_vhosts}}"


  roles:    
    - { role: geerlingguy.apache }
