---
- hosts: webservers
  vars_files: 
    - vars/main.yml
    - vars/apache_customers_settings.yml
  
  pre_tasks:
    - hosts={{ item.hostname }}
    - name: create documentroot on servers
    set_fact:
            file: "{{ apache_vhosts | default([])+ [{'path:': item.documentroot}]}}"
    - name: create vhost files
    set_facts:
            apache_vhosts: "{{ apache_vhosts | default([])+ [{'servername:': item.url, 'documentroot': item.documentroot}]}}"

    with_items: "{{ customers_apache_vhosts }}"
  
#  pre_tasks:
#    - nom: creation du documentroot
#      file: path="{{ item.documentroot }}" state=directory
#      with_items: '{{customers_apache_vhosts}}'


  roles:    
    - { role: geerlingguy.apache }}
