---
- hosts: webservers
  vars_files: 
    - vars/main.yml
  
  pre_tasks:
    - nom: creation du documentroot
      file: path="{{ item.documentroot }}" state=directory
      with_items: '{{apache_vhosts}}'

  roles:    
    - { role: geerlingguy.apache }